package com.FP.Pages;


import com.FP.global.GlobalCommonMethods;

public class NlproWebElementLocators extends GlobalCommonMethods {

	
	//public String NLPRO_Upload_Text_Locator = "xpath=//*[@id='uploadData']//input[@type='file']";
	//public String NLPRO_Upload_Text_Locator = "xpath=//*[form[@id='uploadData']/input[@name='fileName']]";
	public String NLPRO_Upload_Text_Locator = "id=loadTextFile";
	public String NLPRO_Upload_HTML_Locator = "id=htmlParser";
//	public String NLPRO_Upload_Text_Locator = "name=fileName";
	public String NLPRO_Scan_Text_Area_Locator = "id=textEditorData";
	public String NLPRO_Scan_Upload_Data_Form_locator = "css=form";
	//public String NLPRO_Upload_Text_Locator = "id=textEditorData";
	public String NLPRO_Scan_Error_Message_For_Entity_Already_Existing_In_Taxonomy_Locator = "xpath=//*[@id='message-content']";
	public String NLPRO_Select_Person_Sub_Menu_Locator = "xpath=//ul[@class='context-menu-list']//li[@class='context-menu-item'][1]//span[text()='Person']";
    public String NLPRO_Hover_Add_Menu = "xpath=//ul/li[1]/span[text()='Add']";
    public String NLPRO_Hover_Train_Menu = "xpath=//ul[1]/li[3]/span[text()='Train']";
    public String NLPRO_Train_Organization_Menu_Locator = "xpath=//ul[@class='context-menu-list']//li[2]//span[text()='Organization']";
    public String NLPRO_Train_Location_Menu_Locator = "xpath=//ul[@class='context-menu-list']//li[3]//span[text()='Location']";
    public String NLPRO_Train_Person_Menu_Locator = "xpath=//ul[@class='context-menu-list']//li[1]//span[text()='Person']";
    public String NLPRO_On_The_Fly_Train_Select_Template_Name_Locator = "name=templateName";
    public String NLPRO_On_The_Fly_Train_Select_Model_Name_Locator = "id=model";
    public String NLPRO_On_The_Fly_Train_Train_Button_Locator = "id=trainDefaultOption";
    public String NLPRO_Lookup_Organization_Folder_Locator = "xpath=//*[@id='LookupTreeorganization']/button";
    public String NLPRO_Lookup_Extension_Folder_Locator = "xpath=//*[@id='LookupTreeextension']/button";
    public String NLPRO_Lookup_Filter_Folder_Locator = "xpath=//*[@id='LookupTreefilter']/button";
    public String NLPRO_Lookup_Kyc_Folder_Locator = "xpath=//*[@id='LookupTreekyc']/button";
    public String NLPRO_Lookup_Location_Folder_Locator = "xpath=//*[@id='LookupTreelocation']/button";
    public String NLPRO_Lookup_Money_Folder_Locator = "xpath=//*[@id='LookupTreemoney']/button";
    public String NLPRO_Lookup_Person_Folder_Locator = "xpath=//*[@id='LookupTreeperson']/button";
    public String NLPRO_Lookup_Swift_Folder_Locator = "xpath=//*[@id='LookupTreeswift']/button";
    public String NLPRO_Lookup_Titles_Folder_Locator = "xpath=//*[@id='LookupTreetitles']/button";
    public String NLPRO_Lookup_Bank_Names_File_Locator = "xpath=//*[@id='downloadFileBtn0']";
    public String NLPRO_Lookup_Screen_Locator = "xpath=//*[@id='wrapper']/nav/div/div[2]/button[2]";
    public String NLPRO_Affirm_Add_To_Taxonomy_Locator = "id=modalConfirmYes";
    public String NLPRO_Twitter_Feed_Locator = "xpath=//*[@id='getTwitterFeeds']/button";
    public String NLPRO_Hashtag_Checkbox_Locator = "xpath=//*[@id='setInputsForTwitter']/div/div/form/div[1]/div[1]/label/input";
    public String NLPRO_Hashtag_Input_Field_Locator = "xpath=//*[@id='hastagValue']";
    public String NLPRO_Get_Feeds_Button_Locator = "id=twitterDefaultOption";
    public String NLPRO_Invalid_Hashtag_Error_Message_Locator = "xpath=//*[@id='setInputsForTwitter']/div/div/form/div[1]/div[1]/div";
    public String NLPRO_Twitter_Popup_Header_Locator = "xpath=//*[@id='setInputsForTwitter']/div/div/div/h4";
    public String NLPRO_Twitter_Popup_Cancel_Button_Locator = "xpath=//*[@id='setInputsForTwitter']/div/div/form/div[2]/button[2]";
    public String NLPRO_Username_Checkbox_Locator = "xpath=//*[@id='setInputsForTwitter']/div/div/form/div[1]/div[2]/label/input";
    public String NLPRO_Username_Input_Field_Locator = "xpath=//*[@id='setInputsForTwitter']/div/div/form/div[1]/div[2]/input";
    public String NLPRO_Invalid_Username_Error_Message_Locator = "xpath=//*[@id='setInputsForTwitter']/div/div/form/div[1]/div[2]/div";
    public String NLPRO_Process_Button_Locator = "xpath=.//*[@id='process']";
    public String NLPRO_Untag_Menu_Locator = "xpath=//ul/li[@class='context-menu-item']//span[text()='Untag']";
    public String NLPRO_Person_Accordion_Locator = "xpath=//*[@id='PERSON']/div[1]/h4/a/span";
    public String NLPRO_Person_Accordion_value_Locator = "xpath=//div[@id='PERSON']//div[2]//ul//li//span[1]";
    public String NLPRO_Person_Accordion_value_Locator_For_Apricot_Billiboy = "xpath=//div[@id='PERSON']//div[2]//div//ul//li//span[contains(text(),'Apricot Billiboy')]";
    public String NLPRO_Person_Accordion_Value_Count_Locator_For_Apricot_Billiboy = "xpath=//div[@id='PERSON']//div[2]//ul//li[3]//span[2]";
    public String NLPRO_Person_Accordion_value_Locator_For_John_Depp = "xpath=//div[@id='PERSON']//div[2]//ul//li[2]//span[1]";
    public String NLPRO_Person_Accordion_Value_Count_Locator = "xpath=//div[@id='PERSON']//div[2]//ul//li[1]//span[2]";
    public String NLPRO_Person_Accordion_Value_Count_Locator_For_John_Depp = "xpath=//div[@id='PERSON']//div[2]//ul//li[2]//span[2]";
    public String NLPRO_Location_Accordion_value_Locator_For_Gillie_Band = "xpath=//div[@id='LOCATION']//div[2]//ul//li[4]//span[1]";
    public String NLPRO_Location_Accordion_Value_Count_Locator_For_Gillie_Band = "xpath=//div[@id='LOCATION']//div[2]//ul//li[4]//span[2]";
    public String NLPRO_Organization_Accordion_Value_Locator_For_Kunjan_Holdings = "xpath=//div[@id='ORGANIZATION']//div[2]//ul//li[1]//span[1]";
    public String NLPRO_Organization_Accordion_Value_Count_Locator_For_Kunjan_Holdings = "xpath=//div[@id='ORGANIZATION']//div[2]//ul//li[1]//span[2]";
    public String NLPRO_Tagged_Text_In_Editor_Area_Locator = "xpath=//*[@class='marked']";
    public String NLPRO_Location_Accordion_Locator = "xpath=//*[@id='LOCATION']/div[1]/h4/a/span";
    //public String NLPRO_Person_Accordion_Locator = "xpath=//*[@id='PERSON']/div[1]/h4/a/span";
    public String NLPRO_Location_Accordion_Value_Locator = "xpath=//div[@id='LOCATION']//div[2]//ul//li[1]//span[1]";
    public String NLPRO_Location_Accordion_Value_Count_Locator = "xpath=//div[@id='LOCATION']//div[2]//ul//li[1]//span[2]";
    public String NLPRO_Location_Accordion_Value_For_Org_To_Loc_Locator1 = "xpath=//div[@id='LOCATION']//div[2]//ul//li[1]//span[contains(text(), 'Adelaide')]";
    public String NLPRO_Location_Accordion_Value_For_Org_To_Loc_Locator2 = "xpath=//div[@id='LOCATION']//div[2]//ul//li[2]//span[contains(text(), 'Adelanto')]";
    public String NLPRO_Location_Accordion_Value_For_Org_To_Loc_Locator3 = "xpath=//div[@id='LOCATION']//div[2]//ul//li[3]//span[contains(text(), 'Adelboden')]";
    public String NLPRO_Location_Accordion_Value_For_Org_To_Loc_Locator4 = "xpath=//div[@id='LOCATION']//div[2]//ul//li[4]//span[contains(text(), 'Adelphia')]";
    public String NLPRO_Organization_Accordion_Locator = "xpath=//*[@id='ORGANIZATION']/div[1]/h4/a/span";
    public String NLPRO_Organization_Accordion_Value_Locator = "xpath=//div[@id='ORGANIZATION']//div[2]//ul//li//span[1]";
    public String NLPRO_Organization_Accordion_Value_Count_Locator = "xpath=//div[@id='ORGANIZATION']//div[2]//ul//li//span[2]";
    public String NLPRO_Spellcheck_Button_Locator = "xpath=.//*[@id='spellCheck']";
    //public String NLPRO_Spellchecked_Word_In_Text_Area_Locator = "xpath=//section[@id='editorContainer']//div[@id='textEditorData'][2]//span";
    public String NLPRO_Spellchecked_Word_In_Text_Area_Locator = "//*[@class='spellchk']";
    public String NLPRO_Suggestions_Menu_Locator = "xpath=//ul//li[1]//span[text()='Suggestions']";
    public String NLPRO_First_Suggestion_Locator = "xpath=//ul[@class='context-menu-list']//li[@class='context-menu-item'][1]//span[text()='webdrive']";
    public String NLPRO_Second_Suggestion_Locator = "xpath=//ul[@class='context-menu-list']//li[@class='context-menu-item'][2]//span[text()='webdriver']";
    public String NLPRO_Third_Suggestion_Locator = "xpath=//ul[@class='context-menu-list']//li[@class='context-menu-item'][3]//span[text()='webdrivee']";
    public String NLPRO_Add_To_Dictionary_Menu_Locator = "xpath=//html//body//ul[2]//li//span[text()='Add To Dictionary']";
    public String NLPRO_Add_To_Dictionary_Confirmation_Yes_Button_Locator = "id=modalConfirmYes";
    public String NLPRO_Ignore_All_Menu_Locator = "xpath=/html/body/ul[2]/li[1]/span";
    public String NLPRO_Spellcheck_Empty_Editor_Error_Message_Locator = "id=message-content";
    public String NLPRO_Scan_Empty_Editor_Error_Message_Locator = "id=message-content";
    public String NLPRO_Phrases_Scan_Empty_Editor_Error_Message_Locator = "xpath=//div[@class='modal-body']//p[@id='message-content']";
    public String NLPRO_Phrases_Train_Empty_Editor_Error_Message_Locator = "xpath=//div[@class='modal-body']//p[@id='message-content']";
    public String NLPRO_Add_To_Dictionary_Confirmation_No_Button_Locator = "id=modalConfirmNo";
    public String NLPRO_Fragment_Button_Locator = "xpath=.//*[@id='fragment']";
    //public String NLPRO_Fragmented_Text_Locator1 = "id=fragmentRootID1";
    //public String NLPRO_Fragmented_Text_Locator2 = "id=fragmentRootID2";
    public String NLPRO_Fragmented_Text_Locator1 = "xpath=//span[@id='fragmentRootID1']//span[@class='clause-header clause-text ng-scope']";
    public String NLPRO_Fragmented_Text_Locator2 = "xpath=//span[@id='fragmentRootID2']//span[@class='clause-header clause-text ng-scope']";
    public String NLPRO_Fragmented_Text_Locator3 = "xpath=//span[@id='fragmentRootID3']//span[@class='clause-header clause-text ng-scope']";
    public String NLPRO_Fragmented_Text_Locator4 = "xpath=//span[@id='fragmentRootID4']//span[@class='clause-header clause-text ng-scope']";
    public String NLPRO_Fragmented_Text_Locator5 = "xpath=//span[@id='fragmentRootID5']//span[@class='clause-header clause-text ng-scope']";
    public String NLPRO_Fragment_Empty_Editor_Error_Message_Locator = "id=message-content";
    public String NLPRO_Renewal_Clause_Accordion_Locator = "id=RENEWAL CLAUSE";
    public String NLPRO_Renewal_Clause_Accordion_Value_Locator = "xpath=//*[@id='RENEWAL CLAUSE']/div[2]/div/ul/li/span/span";
    public String NLPRO_Termination_Clause_Accordion_Locator = "id=TERMINATION CLAUSE";
    public String NLPRO_Termination_Clause_Accordion_Value_Locator = "xpath=//*[@id='TERMINATION CLAUSE']/div[2]/div/ul/li/span/span";
    public String NLPRO_Refresh_Button_Locator = "xpath=.//*[@id='refreshBtn']";
    public String NLPRO_Select_Location_Sub_Menu_Locator = "xpath=//ul[@class='context-menu-list']//li[@class='context-menu-item'][3]//span[text()='Location']";
    public String NLPRO_Select_Organization_Sub_Menu_Locator = "xpath=//ul[@class='context-menu-list']//li[@class='context-menu-item'][2]//span[text()='Organization']";
    public String NLPRO_Template_Text_Area_Locator = "id=textEditorData";
    public String NLPRO_Template_Create_New_Template_Button_Locator = "id=createNewTemplateBtn";
    public String NLPRO_New_Template_Name_Input_Locator = "id=templateName";
    public String NLPRO_New_Template_Type_Select_Locator = "xpath=//select[@id='modelList']";
    public String NLPRO_New_Template_Save_Template_Locator = "id=saveTemplateDefaultOption";
    public String NLPRO_Select_Available_Person_Template_Locator = "id=selectPERSONTemplate";
    public String NLPRO_Select_Available_Location_Template_Locator = "id=selectLOCATIONTemplate";
    public String NLPRO_Select_Available_Organization_Template_Locator = "id=selectORGANIZATIONTemplate";
    public String NLPRO_Template_Invalid_Corpus_Error_Message_Locator = "id=message-content";
    public String NLPRO_Template_Inline_Error_Message_Locator = "xpath=//div[@class='mrb5']//span";
    public String NLPRO_Template_Empty_Editor_Area_Error_Message_Locator = "id=message-content";
    public String NLPRO_Template_Unsaved_Corpus_Confirmation_Message_Locator = "xpath=//div[@class='modal-body']//p";
    public String NLPRO_Train_Menu_Locator = "xpath=//div[@class='menuOptions']//a[@ui-sref='train']";
    public String NLPRO_Template_Confirmation_Yes_Button_Locator = "id=confirmationMSgYesOption";
    public String NLPRO_Template_Confirmation_No_Button_Locator = "id=confirmationMSgDefaultOption";
    public String NLPRO_Page_Header_Label_Locator = "xpath=//div[@id='container']//p";
    public String NLPRO_Template_Save_Changes_Button_Locator = "id=saveInitialTemplate";
    public String NLPRO_Cancel_New_Template_Creation_Button_Locator = "//button[@class='btn btn-default']";
    public String NLPRO_New_Template_Creation_Popup_Header_Label_Locator = "//div[@class='modal-header popupHeader']//h4";
    public String NLPRO_New_Template_Creation_Popup_Close_Button_Locator = "//div[@class='modal-header popupHeader']//a";
    public String NLPRO_Lookup_Search_Input_Locator = "xpath=//div[@class='search-input']//input";
    public String NLPRO_Lookup_Search_Button_Locator = "xpath=.//*[@id='uploadTaxonomy']/div/button";
    public String NLPRO_Lookup_Search_Result_Text_Locator = "xpath=//div[@class='search-result ng-scope']//i//span[2]";
    public String NLPRO_Lookup_Error_Message_Locator = "xpath=//*[@id='message-content']";
    public String NLPRO_Lookup_Error_Message_Popup_OK_Button_Locator = "//*[@id='modalDefaultOption']";
    public String NLPRO_Lookup_Results_Table_Organization_File_Locator = "xpath=//div[@class='file-details-result-table']//ul//li//span[text()='private_companies_a.txt']";
    public String NLPRO_Lookup_Results_Table_Organization_Filesize_Locator = "xpath=//div[@class='file-details-result-table']//ul//li//span[text()='403 KB']";
    public String NLPRO_Lookup_Results_Table_Organization_Download_File_Button_Locator = "xpath=//div[@class='file-details-result-table']//ul[3]//li[4]//span//button";
    public String NLPRO_Lookup_Results_Table_Organization_Date_Modified_Locator = "xpath=//div[@class='file-details-result-table']//ul//li//span[text()='08/22/2017 11:39:49']";
    public String NLPRO_Lookup_Results_Table_Extension_File_Locator = "xpath=//div[@class='file-details-result-table']//ul[1]//li[1]//span";
    public String NLPRO_Lookup_Results_Table_Extension_Filesize_Locator = "xpath=//div[@class='file-details-result-table']//ul[1]//li[2]//span";
    public String NLPRO_Lookup_Results_Table_Extension_Download_File_Button_Locator = "xpath=.//*[@id='downloadFileBtn0']";
    public String NLPRO_Lookup_Results_Table_Extension_Date_Modified_Locator = "xpath=//div[@class='file-details-result-table']//ul[1]//li[3]//span";
    public String NLPRO_Scan_Settings_Button_Locator = "xpath=.//*[@id='settings']";
    public String NLPRO_Scan_Model_Settings_Sub_Menu_Locator = "//ul[@id='drop-down-menu']//li[1]//a";
    public String NLPRO_Scan_Model_Settings_Left_Side_Select_Locator = "xpath=//div[@class='mrb5']//div[@class='col-md-5'][1]//Select[@id='modelList']";
    public String NLPRO_Scan_Model_Settings_Left_To_Right_Button_locator = "xpath=//div[@class='col-md-2']//button[1]";
    public String NLPRO_Scan_Model_Settings_Process_Button_Locator = "id=processDefaultOption";
    public String NLPRO_Scan_Model_Settings_Cancel_Button_Locator = "//button[@class='btn btn-default']";
    public String NLPRO_Scan_Model_Settings_Header_Label_Locator = "//div[@class='modal-header popupHeader']//span//h4";
    public String NLPRO_Lucene_Search_Input_Locator = "id=searchKey";
    public String NLPRO_Lucene_Search_Button_Locator = "id=searchButton";
    public String NLPRO_Lucene_Search_Results_Locator = "//ul//li[@class='ng-scope'][2]//div[2]";
    public String NLPRO_Lucene_Search_Results_Preceding_Sentence_Locator = "//ul//li[@class='ng-scope'][1]//div[2]";
    public String NLPRO_Lucene_Search_Results_Following_Sentence_Locator = "//ul//li[@class='ng-scope'][3]//div[2]";
    public String NLPRO_Lucene_Search_Results_Copy_To_Editor_Link_Locator = "//ul//li[@class='ng-scope'][2]//div[1]//i";
    public String NLPRO_Lucene_Search_Results_Copy_To_Editor_Link_Preceding_Sentence_Locator = "//ul//li[@class='ng-scope'][1]//div[1]//i";
    public String NLPRO_Lucene_Search_Results_Copy_To_Editor_Link_Following_Sentence_Locator = "//ul//li[@class='ng-scope'][3]//div[1]//i";
    public String NLPRO_Lucene_Failed_Search_Error_Message = "//div[@class='file-details-result-table']//div";
	public String NLPRO_Named_Entity_Train_Text_Area_Locator = "id=textEditorData";
	public String NLPRO_Save_As_Template_Button_Locator = "id=asd";
	public String NLPRO_Phrase_To_Replace_Input_Field_Locator = "id=phraseToReplace";
	public String NLPRO_Phrase_To_Replace_Button_Locator = "id=trainDefaultOption";
	public String NLPRO_Phrase_To_Replace_Inline_Error_Message_Locator = "xpath=//div[@class='inline-error-message ng-binding']";
	public String NLPRO_Phrase_To_Replace_Cancel_Button_Locator = "xpath=//div//button[@class='btn btn-default']";
	public String NLPRO_Phrase_To_Replace_Popup_Header_Label_Locator = "xpath=//div[@class='modal-content']//div//span//h4[text()='Please enter Phrase to be Replaced']";
	public String NLPRO_Save_As_Template_Empty_Editor_Area_Error_Message_Locator = "id=message-content";
	public String NLPRO_Save_As_Template_Unselected_Data_In_Editor_Area_Error_Message_Locator = "id=message-content";
	public String NLPRO_Named_Entity_Train_Page_Train_Button_Locator = "id=train";
	public String NLPRO_Phrases_Train_Page_Train_Button_Locator = "id=train";
	public String NLPRO_Named_Entity_Train_Page_Empty_Editor_Area_Error_Message_Locator = "id=message-content";
	public String NLPRO_Named_Entity_Scan_Upload_HTML_Button_Locator = "xpath=.//*[@id='htmlTextParser']/button";
	public String NLPRO_Named_Entity_Scan_Upload_Text_Button_Locator = "xpath=.//*[@id='uploadData']/button";
	public String NLPRO_Named_Entity_Get_Facebook_Feeds_Button_Locator = "xpath=.//*[@id='getFacebookFeeds']/button";
	public String NLPRO_Named_Entity_Train_Upload_Text_Button_Locator = "xpath=.//*[@id='uploadData']/button";
	public String NLPRO_Named_Entity_Train_Train_Button_Locator = "xpath=.//*[@id='train']";
	public String NLPRO_Named_Entity_Train_Refresh_Button_Locator = "xpath=.//*[@id='refreshBtn']";
	public String NLPRO_Phrases_Scan_Upload_HTML_Button_Locator = "xpath=.//*[@id='htmlTextParser']/button";
	public String NLPRO_Phrases_Scan_Upload_Text_Button_Locator = "xpath=.//*[@id='uploadData']/button";
	public String NLPRO_Phrases_Scan_Process_Button_Locator = "xpath=.//*[@id='process']";
	public String NLPRO_Phrases_Scan_Refresh_Button_Locator = "xpath=.//*[@id='refreshBtn']";
	public String NLPRO_Phrases_Train_Upload_Text_Button_Locator = "xpath=.//*[@id='uploadData']/button";
	public String NLPRO_Phrases_Train_Train_Button_Locator = "xpath=.//*[@id='train']";
	public String NLPRO_Phrases_Train_Refresh_Button_Locator = "xpath=.//*[@id='refreshBtn']";
	public String NLPRO_Lookup_Upload_File_Button_Locator = "xpath=.//*[@id='uploadTaxonomy']/button";
	public String NLPRO_Scan_Header_Menu_Locator = "xpath=.//*[@id='wrapper']/nav/div/div[2]/div[1]/a";
	public String NLPRO_Header_Phrases_Scan_Sub_Menu = "xpath=.//*[@id='wrapper']/nav/div/div[2]/div[1]/div/ul/li[2]/a";
	public String NLPRO_Train_Header_Menu_Locator = "xpath=.//*[@id='wrapper']/nav/div/div[2]/div[2]/a";
	public String NLPRO_Header_Phrases_Train_Sub_Menu = "xpath=.//*[@id='wrapper']/nav/div/div[2]/div[2]/div/ul/li[2]/a";
	public String NLPRO_Template_Screen_Header_Link = "xpath=.//*[@id='wrapper']/nav/div/div[2]/button[1]";
	public String NLPRO_Lookup_Screen_Header_Link = "xpath=.//*[@id='wrapper']/nav/div/div[2]/button[2]";
	public String NLPRO_Named_Entity_Scan_Invalid_File_Upload_Error_Message_Locator = "id=message-content";
	public String NLPRO_Named_Entity_Train_Add_Menu_Locator = "xpath=//ul//li//span[text()='Add']";
	public String NLPRO_Named_Entity_Train_Add_Person_Menu_Locator = "xpath=//ul//li//ul//li//span[text()='Person']";
	public String NLPRO_Named_Entity_Train_Add_Location_Menu_Locator = "xpath=//ul//li//ul//li//span[text()='Location']";
	public String NLPRO_Named_Entity_Train_Add_Organization_Menu_Locator = "xpath=//ul//li//ul//li//span[text()='Organization']";
	public String NLPRO_Named_Entity_Train_Model_Selector_In_Popup_Locator = "id=modelList";
	public String NLPRO_Named_Entity_Train_Process_Button_In_Popup_Locator = "id=processDefaultOption";
	public String NLPRO_On_The_Fly_Training_All_Occurrences_Checkbox_Locator = "xpath=//input[@type='checkbox']";
	
	public String Google_Search_Bar_Locator = "name=q";
	public String Google_Search_Result_Label_Locator = "xpath=//div[@class='tF2Cxc']//div[@class='yuRUbf']//a//h3//span";
}
